server: 
  servlet: 
    context-path: /aspi/
    session: 
      persistent: true
      cookie.name: JSESSIONID_ASPI
  port: 8081
spring:
  threads: 
    virtual:
      enabled: true
  mvc:
    async:
      request-timeout: -1
  servlet: 
    multipart: 
        max-file-size: 5MB
  profiles: 
    active: dev
  application:
    name: aspi
  thymeleaf:
    cache: false
  banner:
    location: banner.txt
  jackson:
   serialization:
     FAIL_ON_EMPTY_BEANS: false
javax: 
  xml: 
    XMLConstants: 
      feature: 
        secure-processing: true
